name: Docker Build, Optimize with DockerSlim, and Push to Docker Hub

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clear Yarn Cache
        run: yarn cache clean

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false  # Do not push yet, optimize first
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_ENV=production

      - name: Install DockerSlim
        run: |
          curl -sL https://downloads.dockerslim.com/releases/1.39.0/dist_linux.tar.gz | tar -xz
          sudo mv dist_linux/docker-slim /usr/local/bin/

      - name: Optimize Docker Image with DockerSlim
        run: |
          docker-slim build --target ${{ steps.meta.outputs.tags }} --tag ${{ steps.meta.outputs.tags }}-slim

      - name: Push Optimized Image to Docker Hub
        run: |
          docker tag ${{ steps.meta.outputs.tags }}-slim ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:slim
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:slim
